/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as SuccessStoriesRouteImport } from './routes/success-stories'
import { Route as StudyAbroadRouteImport } from './routes/study-abroad'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SatRouteImport } from './routes/sat'
import { Route as GreRouteImport } from './routes/gre'
import { Route as GmatRouteImport } from './routes/gmat'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GrePrivateTutoringRouteImport } from './routes/gre/private-tutoring'

const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessStoriesRoute = SuccessStoriesRouteImport.update({
  id: '/success-stories',
  path: '/success-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyAbroadRoute = StudyAbroadRouteImport.update({
  id: '/study-abroad',
  path: '/study-abroad',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SatRoute = SatRouteImport.update({
  id: '/sat',
  path: '/sat',
  getParentRoute: () => rootRouteImport,
} as any)
const GreRoute = GreRouteImport.update({
  id: '/gre',
  path: '/gre',
  getParentRoute: () => rootRouteImport,
} as any)
const GmatRoute = GmatRouteImport.update({
  id: '/gmat',
  path: '/gmat',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GrePrivateTutoringRoute = GrePrivateTutoringRouteImport.update({
  id: '/private-tutoring',
  path: '/private-tutoring',
  getParentRoute: () => GreRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/gmat': typeof GmatRoute
  '/gre': typeof GreRouteWithChildren
  '/sat': typeof SatRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/study-abroad': typeof StudyAbroadRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/testimonials': typeof TestimonialsRoute
  '/gre/private-tutoring': typeof GrePrivateTutoringRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/gmat': typeof GmatRoute
  '/gre': typeof GreRouteWithChildren
  '/sat': typeof SatRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/study-abroad': typeof StudyAbroadRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/testimonials': typeof TestimonialsRoute
  '/gre/private-tutoring': typeof GrePrivateTutoringRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/gmat': typeof GmatRoute
  '/gre': typeof GreRouteWithChildren
  '/sat': typeof SatRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/study-abroad': typeof StudyAbroadRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/testimonials': typeof TestimonialsRoute
  '/gre/private-tutoring': typeof GrePrivateTutoringRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/gmat'
    | '/gre'
    | '/sat'
    | '/sitemap.xml'
    | '/study-abroad'
    | '/success-stories'
    | '/testimonials'
    | '/gre/private-tutoring'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/gmat'
    | '/gre'
    | '/sat'
    | '/sitemap.xml'
    | '/study-abroad'
    | '/success-stories'
    | '/testimonials'
    | '/gre/private-tutoring'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/gmat'
    | '/gre'
    | '/sat'
    | '/sitemap.xml'
    | '/study-abroad'
    | '/success-stories'
    | '/testimonials'
    | '/gre/private-tutoring'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  GmatRoute: typeof GmatRoute
  GreRoute: typeof GreRouteWithChildren
  SatRoute: typeof SatRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudyAbroadRoute: typeof StudyAbroadRoute
  SuccessStoriesRoute: typeof SuccessStoriesRoute
  TestimonialsRoute: typeof TestimonialsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success-stories': {
      id: '/success-stories'
      path: '/success-stories'
      fullPath: '/success-stories'
      preLoaderRoute: typeof SuccessStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-abroad': {
      id: '/study-abroad'
      path: '/study-abroad'
      fullPath: '/study-abroad'
      preLoaderRoute: typeof StudyAbroadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sat': {
      id: '/sat'
      path: '/sat'
      fullPath: '/sat'
      preLoaderRoute: typeof SatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gre': {
      id: '/gre'
      path: '/gre'
      fullPath: '/gre'
      preLoaderRoute: typeof GreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gmat': {
      id: '/gmat'
      path: '/gmat'
      fullPath: '/gmat'
      preLoaderRoute: typeof GmatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gre/private-tutoring': {
      id: '/gre/private-tutoring'
      path: '/private-tutoring'
      fullPath: '/gre/private-tutoring'
      preLoaderRoute: typeof GrePrivateTutoringRouteImport
      parentRoute: typeof GreRoute
    }
  }
}

interface GreRouteChildren {
  GrePrivateTutoringRoute: typeof GrePrivateTutoringRoute
}

const GreRouteChildren: GreRouteChildren = {
  GrePrivateTutoringRoute: GrePrivateTutoringRoute,
}

const GreRouteWithChildren = GreRoute._addFileChildren(GreRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  GmatRoute: GmatRoute,
  GreRoute: GreRouteWithChildren,
  SatRoute: SatRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudyAbroadRoute: StudyAbroadRoute,
  SuccessStoriesRoute: SuccessStoriesRoute,
  TestimonialsRoute: TestimonialsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
