/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as SuccessStoriesRouteImport } from './routes/success-stories'
import { Route as StudyAbroadRouteImport } from './routes/study-abroad'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SatRouteImport } from './routes/sat'
import { Route as GreRouteImport } from './routes/gre'
import { Route as GmatRouteImport } from './routes/gmat'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookConsultationRouteImport } from './routes/book-consultation'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SatIndexRouteImport } from './routes/sat.index'
import { Route as GreIndexRouteImport } from './routes/gre.index'
import { Route as GmatIndexRouteImport } from './routes/gmat.index'
import { Route as SatPlansPricingRouteImport } from './routes/sat.plans-pricing'
import { Route as GreTestPrepCoursesRouteImport } from './routes/gre.test-prep-courses'
import { Route as GrePrivateTutoringRouteImport } from './routes/gre.private-tutoring'
import { Route as GrePlansPricingRouteImport } from './routes/gre.plans-pricing'
import { Route as GreCityRouteImport } from './routes/gre.$city'
import { Route as GmatTopUniversityCutoffRouteImport } from './routes/gmat.top-university-cutoff'
import { Route as GmatPlansPricingRouteImport } from './routes/gmat.plans-pricing'

const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessStoriesRoute = SuccessStoriesRouteImport.update({
  id: '/success-stories',
  path: '/success-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyAbroadRoute = StudyAbroadRouteImport.update({
  id: '/study-abroad',
  path: '/study-abroad',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SatRoute = SatRouteImport.update({
  id: '/sat',
  path: '/sat',
  getParentRoute: () => rootRouteImport,
} as any)
const GreRoute = GreRouteImport.update({
  id: '/gre',
  path: '/gre',
  getParentRoute: () => rootRouteImport,
} as any)
const GmatRoute = GmatRouteImport.update({
  id: '/gmat',
  path: '/gmat',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookConsultationRoute = BookConsultationRouteImport.update({
  id: '/book-consultation',
  path: '/book-consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SatIndexRoute = SatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SatRoute,
} as any)
const GreIndexRoute = GreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GreRoute,
} as any)
const GmatIndexRoute = GmatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GmatRoute,
} as any)
const SatPlansPricingRoute = SatPlansPricingRouteImport.update({
  id: '/plans-pricing',
  path: '/plans-pricing',
  getParentRoute: () => SatRoute,
} as any)
const GreTestPrepCoursesRoute = GreTestPrepCoursesRouteImport.update({
  id: '/test-prep-courses',
  path: '/test-prep-courses',
  getParentRoute: () => GreRoute,
} as any)
const GrePrivateTutoringRoute = GrePrivateTutoringRouteImport.update({
  id: '/private-tutoring',
  path: '/private-tutoring',
  getParentRoute: () => GreRoute,
} as any)
const GrePlansPricingRoute = GrePlansPricingRouteImport.update({
  id: '/plans-pricing',
  path: '/plans-pricing',
  getParentRoute: () => GreRoute,
} as any)
const GreCityRoute = GreCityRouteImport.update({
  id: '/$city',
  path: '/$city',
  getParentRoute: () => GreRoute,
} as any)
const GmatTopUniversityCutoffRoute = GmatTopUniversityCutoffRouteImport.update({
  id: '/top-university-cutoff',
  path: '/top-university-cutoff',
  getParentRoute: () => GmatRoute,
} as any)
const GmatPlansPricingRoute = GmatPlansPricingRouteImport.update({
  id: '/plans-pricing',
  path: '/plans-pricing',
  getParentRoute: () => GmatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/book-consultation': typeof BookConsultationRoute
  '/contact': typeof ContactRoute
  '/gmat': typeof GmatRouteWithChildren
  '/gre': typeof GreRouteWithChildren
  '/sat': typeof SatRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/study-abroad': typeof StudyAbroadRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/testimonials': typeof TestimonialsRoute
  '/gmat/plans-pricing': typeof GmatPlansPricingRoute
  '/gmat/top-university-cutoff': typeof GmatTopUniversityCutoffRoute
  '/gre/$city': typeof GreCityRoute
  '/gre/plans-pricing': typeof GrePlansPricingRoute
  '/gre/private-tutoring': typeof GrePrivateTutoringRoute
  '/gre/test-prep-courses': typeof GreTestPrepCoursesRoute
  '/sat/plans-pricing': typeof SatPlansPricingRoute
  '/gmat/': typeof GmatIndexRoute
  '/gre/': typeof GreIndexRoute
  '/sat/': typeof SatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/book-consultation': typeof BookConsultationRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/study-abroad': typeof StudyAbroadRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/testimonials': typeof TestimonialsRoute
  '/gmat/plans-pricing': typeof GmatPlansPricingRoute
  '/gmat/top-university-cutoff': typeof GmatTopUniversityCutoffRoute
  '/gre/$city': typeof GreCityRoute
  '/gre/plans-pricing': typeof GrePlansPricingRoute
  '/gre/private-tutoring': typeof GrePrivateTutoringRoute
  '/gre/test-prep-courses': typeof GreTestPrepCoursesRoute
  '/sat/plans-pricing': typeof SatPlansPricingRoute
  '/gmat': typeof GmatIndexRoute
  '/gre': typeof GreIndexRoute
  '/sat': typeof SatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/book-consultation': typeof BookConsultationRoute
  '/contact': typeof ContactRoute
  '/gmat': typeof GmatRouteWithChildren
  '/gre': typeof GreRouteWithChildren
  '/sat': typeof SatRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/study-abroad': typeof StudyAbroadRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/testimonials': typeof TestimonialsRoute
  '/gmat/plans-pricing': typeof GmatPlansPricingRoute
  '/gmat/top-university-cutoff': typeof GmatTopUniversityCutoffRoute
  '/gre/$city': typeof GreCityRoute
  '/gre/plans-pricing': typeof GrePlansPricingRoute
  '/gre/private-tutoring': typeof GrePrivateTutoringRoute
  '/gre/test-prep-courses': typeof GreTestPrepCoursesRoute
  '/sat/plans-pricing': typeof SatPlansPricingRoute
  '/gmat/': typeof GmatIndexRoute
  '/gre/': typeof GreIndexRoute
  '/sat/': typeof SatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/book-consultation'
    | '/contact'
    | '/gmat'
    | '/gre'
    | '/sat'
    | '/sitemap.xml'
    | '/study-abroad'
    | '/success-stories'
    | '/testimonials'
    | '/gmat/plans-pricing'
    | '/gmat/top-university-cutoff'
    | '/gre/$city'
    | '/gre/plans-pricing'
    | '/gre/private-tutoring'
    | '/gre/test-prep-courses'
    | '/sat/plans-pricing'
    | '/gmat/'
    | '/gre/'
    | '/sat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/book-consultation'
    | '/contact'
    | '/sitemap.xml'
    | '/study-abroad'
    | '/success-stories'
    | '/testimonials'
    | '/gmat/plans-pricing'
    | '/gmat/top-university-cutoff'
    | '/gre/$city'
    | '/gre/plans-pricing'
    | '/gre/private-tutoring'
    | '/gre/test-prep-courses'
    | '/sat/plans-pricing'
    | '/gmat'
    | '/gre'
    | '/sat'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/book-consultation'
    | '/contact'
    | '/gmat'
    | '/gre'
    | '/sat'
    | '/sitemap.xml'
    | '/study-abroad'
    | '/success-stories'
    | '/testimonials'
    | '/gmat/plans-pricing'
    | '/gmat/top-university-cutoff'
    | '/gre/$city'
    | '/gre/plans-pricing'
    | '/gre/private-tutoring'
    | '/gre/test-prep-courses'
    | '/sat/plans-pricing'
    | '/gmat/'
    | '/gre/'
    | '/sat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  BookConsultationRoute: typeof BookConsultationRoute
  ContactRoute: typeof ContactRoute
  GmatRoute: typeof GmatRouteWithChildren
  GreRoute: typeof GreRouteWithChildren
  SatRoute: typeof SatRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudyAbroadRoute: typeof StudyAbroadRoute
  SuccessStoriesRoute: typeof SuccessStoriesRoute
  TestimonialsRoute: typeof TestimonialsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success-stories': {
      id: '/success-stories'
      path: '/success-stories'
      fullPath: '/success-stories'
      preLoaderRoute: typeof SuccessStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-abroad': {
      id: '/study-abroad'
      path: '/study-abroad'
      fullPath: '/study-abroad'
      preLoaderRoute: typeof StudyAbroadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sat': {
      id: '/sat'
      path: '/sat'
      fullPath: '/sat'
      preLoaderRoute: typeof SatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gre': {
      id: '/gre'
      path: '/gre'
      fullPath: '/gre'
      preLoaderRoute: typeof GreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gmat': {
      id: '/gmat'
      path: '/gmat'
      fullPath: '/gmat'
      preLoaderRoute: typeof GmatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-consultation': {
      id: '/book-consultation'
      path: '/book-consultation'
      fullPath: '/book-consultation'
      preLoaderRoute: typeof BookConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sat/': {
      id: '/sat/'
      path: '/'
      fullPath: '/sat/'
      preLoaderRoute: typeof SatIndexRouteImport
      parentRoute: typeof SatRoute
    }
    '/gre/': {
      id: '/gre/'
      path: '/'
      fullPath: '/gre/'
      preLoaderRoute: typeof GreIndexRouteImport
      parentRoute: typeof GreRoute
    }
    '/gmat/': {
      id: '/gmat/'
      path: '/'
      fullPath: '/gmat/'
      preLoaderRoute: typeof GmatIndexRouteImport
      parentRoute: typeof GmatRoute
    }
    '/sat/plans-pricing': {
      id: '/sat/plans-pricing'
      path: '/plans-pricing'
      fullPath: '/sat/plans-pricing'
      preLoaderRoute: typeof SatPlansPricingRouteImport
      parentRoute: typeof SatRoute
    }
    '/gre/test-prep-courses': {
      id: '/gre/test-prep-courses'
      path: '/test-prep-courses'
      fullPath: '/gre/test-prep-courses'
      preLoaderRoute: typeof GreTestPrepCoursesRouteImport
      parentRoute: typeof GreRoute
    }
    '/gre/private-tutoring': {
      id: '/gre/private-tutoring'
      path: '/private-tutoring'
      fullPath: '/gre/private-tutoring'
      preLoaderRoute: typeof GrePrivateTutoringRouteImport
      parentRoute: typeof GreRoute
    }
    '/gre/plans-pricing': {
      id: '/gre/plans-pricing'
      path: '/plans-pricing'
      fullPath: '/gre/plans-pricing'
      preLoaderRoute: typeof GrePlansPricingRouteImport
      parentRoute: typeof GreRoute
    }
    '/gre/$city': {
      id: '/gre/$city'
      path: '/$city'
      fullPath: '/gre/$city'
      preLoaderRoute: typeof GreCityRouteImport
      parentRoute: typeof GreRoute
    }
    '/gmat/top-university-cutoff': {
      id: '/gmat/top-university-cutoff'
      path: '/top-university-cutoff'
      fullPath: '/gmat/top-university-cutoff'
      preLoaderRoute: typeof GmatTopUniversityCutoffRouteImport
      parentRoute: typeof GmatRoute
    }
    '/gmat/plans-pricing': {
      id: '/gmat/plans-pricing'
      path: '/plans-pricing'
      fullPath: '/gmat/plans-pricing'
      preLoaderRoute: typeof GmatPlansPricingRouteImport
      parentRoute: typeof GmatRoute
    }
  }
}

interface GmatRouteChildren {
  GmatPlansPricingRoute: typeof GmatPlansPricingRoute
  GmatTopUniversityCutoffRoute: typeof GmatTopUniversityCutoffRoute
  GmatIndexRoute: typeof GmatIndexRoute
}

const GmatRouteChildren: GmatRouteChildren = {
  GmatPlansPricingRoute: GmatPlansPricingRoute,
  GmatTopUniversityCutoffRoute: GmatTopUniversityCutoffRoute,
  GmatIndexRoute: GmatIndexRoute,
}

const GmatRouteWithChildren = GmatRoute._addFileChildren(GmatRouteChildren)

interface GreRouteChildren {
  GreCityRoute: typeof GreCityRoute
  GrePlansPricingRoute: typeof GrePlansPricingRoute
  GrePrivateTutoringRoute: typeof GrePrivateTutoringRoute
  GreTestPrepCoursesRoute: typeof GreTestPrepCoursesRoute
  GreIndexRoute: typeof GreIndexRoute
}

const GreRouteChildren: GreRouteChildren = {
  GreCityRoute: GreCityRoute,
  GrePlansPricingRoute: GrePlansPricingRoute,
  GrePrivateTutoringRoute: GrePrivateTutoringRoute,
  GreTestPrepCoursesRoute: GreTestPrepCoursesRoute,
  GreIndexRoute: GreIndexRoute,
}

const GreRouteWithChildren = GreRoute._addFileChildren(GreRouteChildren)

interface SatRouteChildren {
  SatPlansPricingRoute: typeof SatPlansPricingRoute
  SatIndexRoute: typeof SatIndexRoute
}

const SatRouteChildren: SatRouteChildren = {
  SatPlansPricingRoute: SatPlansPricingRoute,
  SatIndexRoute: SatIndexRoute,
}

const SatRouteWithChildren = SatRoute._addFileChildren(SatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  BookConsultationRoute: BookConsultationRoute,
  ContactRoute: ContactRoute,
  GmatRoute: GmatRouteWithChildren,
  GreRoute: GreRouteWithChildren,
  SatRoute: SatRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudyAbroadRoute: StudyAbroadRoute,
  SuccessStoriesRoute: SuccessStoriesRoute,
  TestimonialsRoute: TestimonialsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
